PREFIX fedora-view: <info:fedora/fedora-system:def/view#> 
PREFIX fedora-model: <info:fedora/fedora-system:def/model#> 
PREFIX cdr-base: <http://cdr.unc.edu/definitions/1.0/base-model.xml#> 
ASK 
FROM <%1$s>
WHERE {
    ?pid cdr-base:sourceData ?srcDS .
    OPTIONAL { ?pid cdr-base:techData ?techDS . }
    FILTER ( ?pid = <%2$s> && !bound(?techDS)) 
}