PREFIX fedora-view: <info:fedora/fedora-system:def/view#> 
PREFIX fedora-model: <info:fedora/fedora-system:def/model#> 
PREFIX cdr-base: <http://cdr.unc.edu/definitions/1.0/base-model.xml#>
# Find candidates where the source datastream is newer than the techmd ds 
SELECT ?pid ?label
FROM <%1$s>
WHERE { 
  ?pid cdr-base:sourceData ?srcDS .
  ?pid fedora-model:label ?label . 
  ?srcDS fedora-view:lastModifiedDate ?srcModified . 
  ?pid cdr-base:techData ?techDS . 
  ?techDS fedora-view:lastModifiedDate ?techModified . 
  FILTER ( ?srcModified > ?techModified )
}