version: '3.7'

services:
  activemq:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "46161:61616"
      - "46888:8161"
    environment:
      ANONYMOUS_LOGIN: true
  fedora:
    image: fcrepo/fcrepo:5.1.1-multiplatform
    ports:
      - "48085:8080"
    volumes:
      - /tmp/boxc_test_storage:/tmp/boxc_test_storage
      - ./it_config:/config
    environment:
      CATALINA_OPTS: "-Djava.awt.headless=true -server -Xms1G -Xmx2G -XX:MaxNewSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.external.content.allowed=/config/allowed_external_paths.txt -Dlogback.configurationFile=/config/fcrepo_logback.xml"
    stdin_open: true
    tty: true
  redis:
    image: redis:6
    ports:
      - "46380:6379"
  fuseki:
    # Using this image since fcrepo camel v5 does not support authentication, can switch on fedora 6
    image: atomgraph/fuseki
    ports:
      - "43030:3030"
    command: --mem /test
  solr:
    image: solr:9
    ports:
      - "48983:8983"
    volumes:
      - ./etc/solr-config:/var/solr/data/access/conf
    command:
      - solr-precreate
      - access
      - /var/solr/data/access/conf