PREFIX fedora-view: <info:fedora/fedora-system:def/view#> 
PREFIX fedora-model: <info:fedora/fedora-system:def/model#> 
PREFIX cdr-base: <http://cdr.unc.edu/definitions/1.0/base-model.xml#> 
ASK 
FROM <%1$s>
WHERE { 
    ?pid <info:fedora/fedora-system:def/model#hasModel> <info:fedora/cdr-model:Simple> .
    ?pid cdr-base:sourceData ?srcDS . 
    ?srcDS fedora-view:lastModifiedDate ?srcModified . 
    ?pid cdr-base:hasSourceMimeType ?srcMime .
    ?pid cdr-base:derivedJP2 ?jp2DS . 
    ?jp2DS fedora-view:lastModifiedDate ?jp2Modified . 
    FILTER (
      ?pid = <%2$s> 
      && regex( str(?srcMime), 'image/')
      && ?srcModified > ?jp2Modified 
    ) 
}