package edu.unc.lib.dl.rdf; 

import static com.hp.hpl.jena.rdf.model.ResourceFactory.createProperty;
import static com.hp.hpl.jena.rdf.model.ResourceFactory.createResource;

import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /Users/bbpennel/Desktop/cdr-schemas/cdrDeposit.rdf 
 * @author Auto-generated by schemagen on 05 May 2016 10:57 
 */
public class CdrDeposit {
    
    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://cdr.unc.edu/definitions/model#";
    
    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );
    
    /** File path suggested for cleanup after the deposit has been ingested */
    public static final Property cleanupLocation = createProperty( "http://cdr.unc.edu/definitions/model#cleanupLocation" );
    
    /** Created timestamp of this file on its original storage */
    public static final Property createTime = createProperty( "http://cdr.unc.edu/definitions/model#createTime" );
    
    /** Filename to provide for this object in the repository */
    public static final Property label = createProperty( "http://cdr.unc.edu/definitions/model#label" );
    
    /** MD5 checksum for this binary object */
    public static final Property md5sum = createProperty( "http://cdr.unc.edu/definitions/model#md5sum" );
    
    /** Provided mimetype for this binary object */
    public static final Property mimetype = createProperty( "http://cdr.unc.edu/definitions/model#mimetype" );
    
    /** RDF resource type for this object */
    public static final Property objectType = createProperty( "http://cdr.unc.edu/definitions/model#objectType" );
    
    /** Location URI for this object in its original storage location */
    public static final Property originalLocation = createProperty( "http://cdr.unc.edu/definitions/model#originalLocation" );
    
    /** SHA1 checksum for this binary object */
    public static final Property sha1sum = createProperty( "http://cdr.unc.edu/definitions/model#sha1sum" );
    
    /** Filesize in bytes for this binary object */
    public static final Property size = createProperty( "http://cdr.unc.edu/definitions/model#size" );
    
    /** Path to the staged content for ingest. */
    public static final Property stagingLocation = createProperty( "http://cdr.unc.edu/definitions/model#stagingLocation" );
    
}
