/**
 * Copyright 2008 The University of North Carolina at Chapel Hill
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.unc.lib.dl.rdf;

import static org.apache.jena.rdf.model.ResourceFactory.createProperty;
import static org.apache.jena.rdf.model.ResourceFactory.createResource;

import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from /Users/bbpennel/Desktop/cdr-schemas/cdrDeposit.rdf
 * @author Auto-generated by schemagen on 05 May 2016 10:57
 */
public class CdrDeposit {
    private CdrDeposit() {
    }

    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://cdr.unc.edu/definitions/deposit#";

    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {
        return NS; }

    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );

    /** File path suggested for cleanup after the deposit has been ingested */
    public static final Property cleanupLocation = createProperty(
            "http://cdr.unc.edu/definitions/deposit#cleanupLocation" );

    /** Created timestamp of this file on its original storage */
    public static final Property createTime = createProperty(
            "http://cdr.unc.edu/definitions/deposit#createTime" );

    /** Filename to provide for this object in the repository */
    public static final Property label = createProperty(
            "http://cdr.unc.edu/definitions/deposit#label" );

    /** MD5 checksum for this binary object */
    public static final Property md5sum = createProperty(
            "http://cdr.unc.edu/definitions/deposit#md5sum" );

    /** Provided mimetype for this binary object */
    public static final Property mimetype = createProperty(
            "http://cdr.unc.edu/definitions/deposit#mimetype" );

    /** RDF resource type for this object */
    public static final Property objectType = createProperty(
            "http://cdr.unc.edu/definitions/deposit#objectType" );

    /** Location URI for this object in its original storage location */
    public static final Property originalLocation = createProperty(
            "http://cdr.unc.edu/definitions/deposit#originalLocation" );

    /** SHA1 checksum for this binary object */
    public static final Property sha1sum = createProperty(
            "http://cdr.unc.edu/definitions/deposit#sha1sum" );

    /** Filesize in bytes for this binary object */
    public static final Property size = createProperty(
            "http://cdr.unc.edu/definitions/deposit#size" );

    /** Path to the staged content for ingest. */
    public static final Property stagingLocation = createProperty(
            "http://cdr.unc.edu/definitions/deposit#stagingLocation" );

    /** Link to binary objects contained by this object other than the main payload binary. */
    public static final Property hasDatastream = createProperty(
            "http://cdr.unc.edu/definitions/deposit#hasDatastream" );

    /** >Link to a manifest file for this deposit. */
    public static final Property hasManifest = createProperty(
            "http://cdr.unc.edu/definitions/deposit#hasManifest" );

    public static final Property hasSourceMetadata = createProperty(
            "http://cdr.unc.edu/definitions/deposit#hasSourceMetadata");
}
