/**
 * Copyright 2008 The University of North Carolina at Chapel Hill
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.unc.lib.dl.rdf;

import static org.apache.jena.rdf.model.ResourceFactory.createProperty;
import static org.apache.jena.rdf.model.ResourceFactory.createResource;

import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from rdf-schemas/dcElements.rdf
 * @author Auto-generated by schemagen on 10 May 2016 16:33
 */
public class DcElements {
    private DcElements() {
    }

    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://purl.org/dc/elements/1.1/";

    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {
        return NS; }

    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );

    /** An entity responsible for making contributions to the resource. */
    public static final Property contributor = createProperty( "http://purl.org/dc/elements/1.1/contributor" );

    /** The spatial or temporal topic of the resource, the spatial applicability of
     *  the resource, or the jurisdiction under which the resource is relevant.
     */
    public static final Property coverage = createProperty( "http://purl.org/dc/elements/1.1/coverage" );

    /** An entity primarily responsible for making the resource. */
    public static final Property creator = createProperty( "http://purl.org/dc/elements/1.1/creator" );

    /** A point or period of time associated with an event in the lifecycle of the
     *  resource.
     */
    public static final Property date = createProperty( "http://purl.org/dc/elements/1.1/date" );

    /** An account of the resource. */
    public static final Property description = createProperty( "http://purl.org/dc/elements/1.1/description" );

    /** The file format, physical medium, or dimensions of the resource. */
    public static final Property format = createProperty( "http://purl.org/dc/elements/1.1/format" );

    /** An unambiguous reference to the resource within a given context. */
    public static final Property identifier = createProperty( "http://purl.org/dc/elements/1.1/identifier" );

    /** A language of the resource. */
    public static final Property language = createProperty( "http://purl.org/dc/elements/1.1/language" );

    /** An entity responsible for making the resource available. */
    public static final Property publisher = createProperty( "http://purl.org/dc/elements/1.1/publisher" );

    /** A related resource. */
    public static final Property relation = createProperty( "http://purl.org/dc/elements/1.1/relation" );

    /** Information about rights held in and over the resource. */
    public static final Property rights = createProperty( "http://purl.org/dc/elements/1.1/rights" );

    /** A related resource from which the described resource is derived. */
    public static final Property source = createProperty( "http://purl.org/dc/elements/1.1/source" );

    /** The topic of the resource. */
    public static final Property subject = createProperty( "http://purl.org/dc/elements/1.1/subject" );

    /** A name given to the resource. */
    public static final Property title = createProperty( "http://purl.org/dc/elements/1.1/title" );

    /** The nature or genre of the resource. */
    public static final Property type = createProperty( "http://purl.org/dc/elements/1.1/type" );

}
