/**
 * Copyright 2008 The University of North Carolina at Chapel Hill
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.unc.lib.dl.rdf;

import static org.apache.jena.rdf.model.ResourceFactory.createProperty;
import static org.apache.jena.rdf.model.ResourceFactory.createResource;

import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from rdf-schemas/ianaRelation.rdf
 * @author Auto-generated by schemagen on 21 Apr 2016 12:16
 */
public class IanaRelation {
    private IanaRelation() {

    }

    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://www.iana.org/assignments/relation/";

    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {
        return NS; }

    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );

    /** Refers to a resource that is the subject of the link's context. */
    public static final Property about = createProperty( "http://www.iana.org/assignments/relation/about" );

    /** Refers to a substitute for this context */
    public static final Property alternate = createProperty( "http://www.iana.org/assignments/relation/alternate" );

    /** Refers to an appendix. */
    public static final Property appendix = createProperty( "http://www.iana.org/assignments/relation/appendix" );

    /** Refers to a collection of records, documents, or other materials of historical
     *  interest.
     */
    public static final Property archives = createProperty( "http://www.iana.org/assignments/relation/archives" );

    /** Refers to the context's author. */
    public static final Property author = createProperty( "http://www.iana.org/assignments/relation/author" );

    /** Gives a permanent link to use for bookmarking purposes. */
    public static final Property bookmark = createProperty( "http://www.iana.org/assignments/relation/bookmark" );

    /** Designates the preferred version of a resource (the IRI and its contents). */
    public static final Property canonical = createProperty( "http://www.iana.org/assignments/relation/canonical" );

    /** Refers to a chapter in a collection of resources. */
    public static final Property chapter = createProperty( "http://www.iana.org/assignments/relation/chapter" );

    /** The target IRI points to a resource which represents the collection resource
     *  for the context IRI.
     */
    public static final Property collection = createProperty( "http://www.iana.org/assignments/relation/collection" );

    /** Refers to a table of contents. */
    public static final Property contents = createProperty( "http://www.iana.org/assignments/relation/contents" );

    /** Refers to a copyright statement that applies to the link's context. */
    public static final Property copyright = createProperty( "http://www.iana.org/assignments/relation/copyright" );

    /** The target IRI points to a resource where a submission form can be obtained. */
    public static final Property create_form = createProperty( "http://www.iana.org/assignments/relation/create-form" );

    /** Refers to a resource containing the most recent item(s) in a collection of
     *  resources.
     */
    public static final Property current = createProperty( "http://www.iana.org/assignments/relation/current" );

    /** The target IRI points to a resource from which this material was derived. */
    public static final Property derivedfrom = createProperty( "http://www.iana.org/assignments/relation/derivedfrom" );

    /** Refers to a resource providing information about the link's context. */
    public static final Property describedby = createProperty( "http://www.iana.org/assignments/relation/describedby" );

    /** The relationship A 'describes' B asserts that resource A provides a description
     *  of resource B. There are no constraints on the format or representation of
     *  either A or B, neither are there any further constraints on either resource.
     */
    public static final Property describes = createProperty( "http://www.iana.org/assignments/relation/describes" );

    /** Refers to a list of patent disclosures made with respect to material for which
     *  'disclosure' relation is specified.
     */
    public static final Property disclosure = createProperty( "http://www.iana.org/assignments/relation/disclosure" );

    /** Refers to a resource whose available representations are byte-for-byte identical
     *  with the corresponding representations of the context IRI.
     */
    public static final Property duplicate = createProperty( "http://www.iana.org/assignments/relation/duplicate" );

    /** Refers to a resource that can be used to edit the link's context. */
    public static final Property edit = createProperty( "http://www.iana.org/assignments/relation/edit" );

    /** The target IRI points to a resource where a submission form for editing associated
     *  resource can be obtained.
     */
    public static final Property edit_form = createProperty( "http://www.iana.org/assignments/relation/edit-form" );

    /** Refers to a resource that can be used to edit media associated with the link's
     *  context.
     */
    public static final Property edit_media = createProperty( "http://www.iana.org/assignments/relation/edit-media" );

    /** Identifies a related resource that is potentially large and might require
     *  special handling.
     */
    public static final Property enclosure = createProperty( "http://www.iana.org/assignments/relation/enclosure" );

    /** An IRI that refers to the furthest preceding resource in a series of resources. */
    public static final Property first = createProperty( "http://www.iana.org/assignments/relation/first" );

    /** Refers to a glossary of terms. */
    public static final Property glossary = createProperty( "http://www.iana.org/assignments/relation/glossary" );

    /** Refers to context-sensitive help. */
    public static final Property help = createProperty( "http://www.iana.org/assignments/relation/help" );

    /** Refers to a resource hosted by the server indicated by the link context. */
    public static final Property hosts = createProperty( "http://www.iana.org/assignments/relation/hosts" );

    /** Refers to a hub that enables registration for notification of updates to the
     *  context.
     */
    public static final Property hub = createProperty( "http://www.iana.org/assignments/relation/hub" );

    /** Refers to an icon representing the link's context. */
    public static final Property icon = createProperty( "http://www.iana.org/assignments/relation/icon" );

    /** Refers to an index. */
    public static final Property index = createProperty( "http://www.iana.org/assignments/relation/index" );

    /** The target IRI points to a resource that is a member of the collection represented
     *  by the context IRI.
     */
    public static final Property item = createProperty( "http://www.iana.org/assignments/relation/item" );

    /** An IRI that refers to the furthest following resource in a series of resources. */
    public static final Property last = createProperty( "http://www.iana.org/assignments/relation/last" );

    /** Points to a resource containing the latest (e.g., current) version of the
     *  context.
     */
    public static final Property latest_version = createProperty(
            "http://www.iana.org/assignments/relation/latest-version" );

    /** Refers to a license associated with this context. */
    public static final Property license = createProperty( "http://www.iana.org/assignments/relation/license" );

    /** Refers to further information about the link's context, expressed as a LRDD
     *  ("Link-based Resource Descriptor Document") resource. See for information
     *  about processing this relation type in host-meta documents. When used elsewhere,
     *  it refers to additional links and other metadata. Multiple instances indicate
     *  additional LRDD resources. LRDD resources MUST have an "application/xrd+xml"
     *  representation, and MAY have others.
     */
    public static final Property lrdd = createProperty( "http://www.iana.org/assignments/relation/lrdd" );

    /** The Target IRI points to a Memento, a fixed resource that will not change
     *  state anymore.
     */
    public static final Property memento = createProperty( "http://www.iana.org/assignments/relation/memento" );

    /** Refers to a resource that can be used to monitor changes in an HTTP resource. */
    public static final Property monitor = createProperty( "http://www.iana.org/assignments/relation/monitor" );

    /** Refers to a resource that can be used to monitor changes in a specified group
     *  of HTTP resources.
     */
    public static final Property monitor_group = createProperty(
            "http://www.iana.org/assignments/relation/monitor-group" );

    /** Indicates that the link's context is a part of a series, and that the next
     *  in the series is the link target.
     */
    public static final Property next = createProperty( "http://www.iana.org/assignments/relation/next" );

    /** Refers to the immediately following archive resource. */
    public static final Property next_archive = createProperty(
            "http://www.iana.org/assignments/relation/next-archive" );

    /** Indicates that the context’s original author or publisher does not endorse
     *  the link target.
     */
    public static final Property nofollow = createProperty( "http://www.iana.org/assignments/relation/nofollow" );

    /** Indicates that no referrer information is to be leaked when following the
     *  link.
     */
    public static final Property noreferrer = createProperty( "http://www.iana.org/assignments/relation/noreferrer" );

    /** The Target IRI points to an Original Resource. */
    public static final Property original = createProperty( "http://www.iana.org/assignments/relation/original" );

    /** Indicates a resource where payment is accepted. */
    public static final Property payment = createProperty( "http://www.iana.org/assignments/relation/payment" );

    /** Points to a resource containing the predecessor version in the version history. */
    public static final Property predecessor_version = createProperty(
            "http://www.iana.org/assignments/relation/predecessor-version" );

    /** Indicates that the link target should be preemptively cached. */
    public static final Property prefetch = createProperty( "http://www.iana.org/assignments/relation/prefetch" );

    /** Indicates that the link's context is a part of a series, and that the previous
     *  in the series is the link target.
     */
    public static final Property prev = createProperty( "http://www.iana.org/assignments/relation/prev" );

    /** Refers to the immediately preceding archive resource. */
    public static final Property prev_archive = createProperty(
            "http://www.iana.org/assignments/relation/prev-archive" );

    /** Refers to a resource that provides a preview of the link's context. */
    public static final Property preview = createProperty( "http://www.iana.org/assignments/relation/preview" );

    /** Refers to the previous resource in an ordered series of resources. Synonym
     *  for "prev".
     */
    public static final Property previous = createProperty( "http://www.iana.org/assignments/relation/previous" );

    /** Refers to a privacy policy associated with the link's context. */
    public static final Property privacy_policy = createProperty(
            "http://www.iana.org/assignments/relation/privacy-policy" );

    /** Identifying that a resource representation conforms to a certain profile,
     *  without affecting the non-profile semantics of the resource representation.
     */
    public static final Property profile = createProperty( "http://www.iana.org/assignments/relation/profile" );

    /** Identifies a related resource. */
    public static final Property related = createProperty( "http://www.iana.org/assignments/relation/related" );

    /** Identifies a resource that is a reply to the context of the link. */
    public static final Property replies = createProperty( "http://www.iana.org/assignments/relation/replies" );

    /** Refers to a resource that can be used to search through the link's context
     *  and related resources.
     */
    public static final Property search = createProperty( "http://www.iana.org/assignments/relation/search" );

    /** Refers to a section in a collection of resources. */
    public static final Property section = createProperty( "http://www.iana.org/assignments/relation/section" );

    /** Conveys an identifier for the link's context. */
    public static final Property self = createProperty( "http://www.iana.org/assignments/relation/self" );

    /** Indicates a URI that can be used to retrieve a service document. */
    public static final Property service = createProperty( "http://www.iana.org/assignments/relation/service" );

    /** Refers to the first resource in a collection of resources. */
    public static final Property start = createProperty( "http://www.iana.org/assignments/relation/start" );

    /** Refers to a stylesheet. */
    public static final Property stylesheet = createProperty( "http://www.iana.org/assignments/relation/stylesheet" );

    /** Refers to a resource serving as a subsection in a collection of resources. */
    public static final Property subsection = createProperty(
            "http://www.iana.org/assignments/relation/subsection");

    /** Points to a resource containing the successor version in the version history. */
    public static final Property successor_version = createProperty(
            "http://www.iana.org/assignments/relation/successor-version");

    /** Gives a tag (identified by the given address) that applies to the current
     *  document.
     */
    public static final Property tag = createProperty( "http://www.iana.org/assignments/relation/tag" );

    /** Refers to the terms of service associated with the link's context. */
    public static final Property terms_of_service = createProperty(
            "http://www.iana.org/assignments/relation/terms-of-service");

    /** The Target IRI points to a TimeGate for an Original Resource. */
    public static final Property timegate = createProperty( "http://www.iana.org/assignments/relation/timegate" );

    /** The Target IRI points to a TimeMap for an Original Resource. */
    public static final Property timemap = createProperty( "http://www.iana.org/assignments/relation/timemap" );

    /** Refers to a resource identifying the abstract semantic type of which the link's
     *  context is considered to be an instance.
     */
    public static final Property type = createProperty( "http://www.iana.org/assignments/relation/type" );

    /** Refers to a parent document in a hierarchy of documents. */
    public static final Property up = createProperty( "http://www.iana.org/assignments/relation/up" );

    /** Points to a resource containing the version history for the context. */
    public static final Property version_history = createProperty(
            "http://www.iana.org/assignments/relation/version-history");

    /** Identifies a resource that is the source of the information in the link's
     *  context.
     */
    public static final Property via = createProperty( "http://www.iana.org/assignments/relation/via" );

    /** Points to a working copy for this resource. */
    public static final Property working_copy = createProperty("http://www.iana.org/assignments/relation/working-copy");

    /** Points to the versioned resource from which this working copy was obtained. */
    public static final Property working_copy_of = createProperty(
            "http://www.iana.org/assignments/relation/working-copy-of");

}
