package edu.unc.lib.dl.rdf; 

import static com.hp.hpl.jena.rdf.model.ResourceFactory.createProperty;
import static com.hp.hpl.jena.rdf.model.ResourceFactory.createResource;

import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from rdf-schemas/pcdmUse.rdf 
 * @author Auto-generated by schemagen on 21 Apr 2016 12:16 
 */
public class PcdmUse {
    
    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://pcdm.org/use#";
    
    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );
    
}
