package edu.unc.lib.dl.rdf; 

import static com.hp.hpl.jena.rdf.model.ResourceFactory.createProperty;
import static com.hp.hpl.jena.rdf.model.ResourceFactory.createResource;

import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from rdf-schemas/premis.rdf 
 * @author Auto-generated by schemagen on 21 Apr 2016 12:16 
 */
public class Premis {
    
    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://www.loc.gov/premis/rdf/v1#";
    
    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );
    
    /** The ontology's owl:versionInfo as a string */
    public static final String VERSION_INFO = "version 2.2.1";
    
    /** The Agent entity aggregates information about attributes or characteristics 
     *  of agents (persons, organizations, or software) associated with rights management 
     *  and preservation events in the life of a data object. Agent information serves 
     *  to identify an agent unambiguously from all other Agent entities.
     */
    public static final Resource Agent = createResource( "http://www.loc.gov/premis/rdf/v1#Agent" );
    
    public static final Resource ApplicableDates = createResource( "http://www.loc.gov/premis/rdf/v1#ApplicableDates" );
    
    public static final Resource Bitstream = createResource( "http://www.loc.gov/premis/rdf/v1#Bitstream" );
    
    public static final Resource ContentLocation = createResource( "http://www.loc.gov/premis/rdf/v1#ContentLocation" );
    
    public static final Resource CopyrightInformation = createResource( "http://www.loc.gov/premis/rdf/v1#CopyrightInformation" );
    
    public static final Resource CreatingApplication = createResource( "http://www.loc.gov/premis/rdf/v1#CreatingApplication" );
    
    public static final Resource Dependency = createResource( "http://www.loc.gov/premis/rdf/v1#Dependency" );
    
    public static final Resource Environment = createResource( "http://www.loc.gov/premis/rdf/v1#Environment" );
    
    /** The Event entity aggregates information about an action that involves one 
     *  or more Object entities. Metadata about an Event would normally be recorded 
     *  and stored separately from the digital object. Whether or not a preservation 
     *  repository records an Event depends upon the importance of the event. Actions 
     *  that modify objects should always be recorded. Other actions such as copying 
     *  an object for backup purposes may be recorded in system logs or an audit trail 
     *  but not necessarily in an Event entity. Mandatory semantic units are: eventIdentifier, 
     *  eventType, and eventDateTime.
     */
    public static final Resource Event = createResource( "http://www.loc.gov/premis/rdf/v1#Event" );
    
    public static final Resource EventOutcomeDetail = createResource( "http://www.loc.gov/premis/rdf/v1#EventOutcomeDetail" );
    
    public static final Resource EventOutcomeInformation = createResource( "http://www.loc.gov/premis/rdf/v1#EventOutcomeInformation" );
    
    public static final Resource File = createResource( "http://www.loc.gov/premis/rdf/v1#File" );
    
    public static final Resource Fixity = createResource( "http://www.loc.gov/premis/rdf/v1#Fixity" );
    
    public static final Resource Format = createResource( "http://www.loc.gov/premis/rdf/v1#Format" );
    
    public static final Resource FormatDesignation = createResource( "http://www.loc.gov/premis/rdf/v1#FormatDesignation" );
    
    public static final Resource FormatRegistry = createResource( "http://www.loc.gov/premis/rdf/v1#FormatRegistry" );
    
    public static final Resource Hardware = createResource( "http://www.loc.gov/premis/rdf/v1#Hardware" );
    
    /** This class is used in PREMIS OWL to describe identifiers if the identifiers 
     *  are not http URIs.
     */
    public static final Resource Identifier = createResource( "http://www.loc.gov/premis/rdf/v1#Identifier" );
    
    public static final Resource Inhibitors = createResource( "http://www.loc.gov/premis/rdf/v1#Inhibitors" );
    
    /** Intellectual entities are described via Descriptive metadata models. These 
     *  are very domain-specific and are out of scope for PREMIS. Examples: Dublin 
     *  Core, Mets, MARC
     */
    public static final Resource IntellectualEntity = createResource( "http://www.loc.gov/premis/rdf/v1#IntellectualEntity" );
    
    public static final Resource LicenseInformation = createResource( "http://www.loc.gov/premis/rdf/v1#LicenseInformation" );
    
    /** The object class aggregates information about a digital object held by a preservation 
     *  repository and describes those characteristics relevant to preservation management. 
     *  The only mandatory property is objectIdentifier. The object class has three 
     *  subclasses: Representation, File, and Bitstream.
     */
    public static final Resource Object = createResource( "http://www.loc.gov/premis/rdf/v1#Object" );
    
    public static final Resource ObjectCharacteristics = createResource( "http://www.loc.gov/premis/rdf/v1#ObjectCharacteristics" );
    
    public static final Resource PremisEntity = createResource( "http://www.loc.gov/premis/rdf/v1#PremisEntity" );
    
    public static final Resource PreservationLevel = createResource( "http://www.loc.gov/premis/rdf/v1#PreservationLevel" );
    
    public static final Resource RelatedObjectIdentification = createResource( "http://www.loc.gov/premis/rdf/v1#RelatedObjectIdentification" );
    
    public static final Resource Representation = createResource( "http://www.loc.gov/premis/rdf/v1#Representation" );
    
    public static final Resource RightsDocumentation = createResource( "http://www.loc.gov/premis/rdf/v1#RightsDocumentation" );
    
    public static final Resource RightsGranted = createResource( "http://www.loc.gov/premis/rdf/v1#RightsGranted" );
    
    /** Extensions: In OWL one can define its own subclasses to the the RightsStatement 
     *  class to denote OtherRightsInformation of the PREMIS data dictionary.
     */
    public static final Resource RightsStatement = createResource( "http://www.loc.gov/premis/rdf/v1#RightsStatement" );
    
    public static final Resource Signature = createResource( "http://www.loc.gov/premis/rdf/v1#Signature" );
    
    public static final Resource SignificantProperties = createResource( "http://www.loc.gov/premis/rdf/v1#SignificantProperties" );
    
    public static final Resource Software = createResource( "http://www.loc.gov/premis/rdf/v1#Software" );
    
    public static final Resource StatuteInformation = createResource( "http://www.loc.gov/premis/rdf/v1#StatuteInformation" );
    
    public static final Resource Storage = createResource( "http://www.loc.gov/premis/rdf/v1#Storage" );
    
    public static final Resource TermOfGrant = createResource( "http://www.loc.gov/premis/rdf/v1#TermOfGrant" );
    
    public static final Resource TermOfRestriction = createResource( "http://www.loc.gov/premis/rdf/v1#TermOfRestriction" );
    
}
