/**
 * Copyright 2008 The University of North Carolina at Chapel Hill
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.unc.lib.dl.rdf;

import static org.apache.jena.rdf.model.ResourceFactory.createProperty;
import static org.apache.jena.rdf.model.ResourceFactory.createResource;

import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from rdf-schemas/rdf.rdf
 * @author Auto-generated by schemagen on 21 Apr 2016 14:52
 */
public class Rdf {

    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://www.w3.org/2000/01/rdf-schema#";

    private Rdf() {
    }

    /** The namespace of the vocabulary as a string
     *  @see #NS */
    public static String getURI() {
        return NS;
    }

    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = createResource( NS );

    /** A description of the subject resource. */
    public static final Property comment = createProperty( "http://www.w3.org/2000/01/rdf-schema#comment" );

    /** A domain of the subject property. */
    public static final Property domain = createProperty( "http://www.w3.org/2000/01/rdf-schema#domain" );

    /** The defininition of the subject resource. */
    public static final Property isDefinedBy = createProperty( "http://www.w3.org/2000/01/rdf-schema#isDefinedBy" );

    /** A human-readable name for the subject. */
    public static final Property label = createProperty( "http://www.w3.org/2000/01/rdf-schema#label" );

    /** A member of the subject resource. */
    public static final Property member = createProperty( "http://www.w3.org/2000/01/rdf-schema#member" );

    /** A range of the subject property. */
    public static final Property range = createProperty( "http://www.w3.org/2000/01/rdf-schema#range" );

    /** Further information about the subject resource. */
    public static final Property seeAlso = createProperty( "http://www.w3.org/2000/01/rdf-schema#seeAlso" );

    /** The subject is a subclass of a class. */
    public static final Property subClassOf = createProperty( "http://www.w3.org/2000/01/rdf-schema#subClassOf" );

    /** The subject is a subproperty of a property. */
    public static final Property subPropertyOf = createProperty( "http://www.w3.org/2000/01/rdf-schema#subPropertyOf" );

}
