PREFIX fedora-view: <info:fedora/fedora-system:def/view#> 
PREFIX fedora-model: <info:fedora/fedora-system:def/model#> 
PREFIX cdr-base: <http://cdr.unc.edu/definitions/1.0/base-model.xml#> 
# surrogate image ds modified after thumb ds
SELECT ?pid ?label
FROM <%1$s>
WHERE {
   ?pid cdr-base:hasSurrogate ?srg .
   ?pid fedora-model:label ?label .
   ?srg cdr-base:sourceData ?srcDS . 
   ?srcDS fedora-view:lastModifiedDate ?srcModified . 
   ?srg cdr-base:hasSourceMimeType ?srcMime .
   ?pid cdr-base:thumb ?thumbDS . 
   ?thumbDS fedora-view:lastModifiedDate ?thumbModified . 
   FILTER ( 
     regex( str(?srcMime), 'image/')
     && ?srcModified > ?thumbModified 
   ) 
}