server "default", :roles => [:web]

# Return SSH options with one key -- a path to the SSH configuration generated by Vagrant.

set :ssh_options, lambda {
  
  if ENV["VAGRANT_CWD"].nil?
    raise "The VAGRANT_CWD environment variable must be set"
  end
  
  unless File.exist?(File.join(ENV["VAGRANT_CWD"], "Vagrantfile"))
    raise "The directory specified by the VAGRANT_CWD environment variable must contain a Vagrantfile"
  end
  
  config = `vagrant ssh-config --host default`
  
  if config == ""
    raise "vagrant ssh-config returned an invalid configuration -- is VAGRANT_CWD set correctly?"
  end
  
  File.open("./ssh_config", "w+") do |f|
    f.write(config)
  end
  
  { :config => "./ssh_config" }
  
}
