<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
<xsl:output indent="yes" method="xml" version="1.0" encoding="UTF-8"/>

<!--
Template iso-639-1-converter
Parameter: languageCode - string
Returns: String with ISO 639-2/B language code corresponding to $languageCode.
Input string, if there is no match.
-->
<xsl:template name="iso-639-1-converter">
<xsl:variable name="languageCode" select="/DISS_submission/DISS_description/DISS_categorization/DISS_language"/>
						<xsl:variable name="lowerCaseLanguageCode" select="translate(
							$languageCode,
							'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
							'abcdefghijklmnopqrstuvwxyz' )"/>
						<xsl:variable name="myLanguageCode" select="$lowerCaseLanguageCode"/>
							<xsl:choose>
								<xsl:when test="string-length($myLanguageCode) = 3">
									<xsl:value-of select="$myLanguageCode"/>
								</xsl:when>
								<xsl:when test="$myLanguageCode = 'ab'">abk</xsl:when>
								<xsl:when test="$myLanguageCode = 'aa'">aar</xsl:when>
								<xsl:when test="$myLanguageCode = 'af'">afr</xsl:when>
								<xsl:when test="$myLanguageCode = 'ak'">aka</xsl:when>
								<xsl:when test="$myLanguageCode = 'sq'">alb</xsl:when>
								<xsl:when test="$myLanguageCode = 'am'">amh</xsl:when>
								<xsl:when test="$myLanguageCode = 'ar'">ara</xsl:when>
								<xsl:when test="$myLanguageCode = 'an'">arg</xsl:when>
								<xsl:when test="$myLanguageCode = 'hy'">arm</xsl:when>
								<xsl:when test="$myLanguageCode = 'as'">asm</xsl:when>
								<xsl:when test="$myLanguageCode = 'av'">ava</xsl:when>
								<xsl:when test="$myLanguageCode = 'ae'">ave</xsl:when>
								<xsl:when test="$myLanguageCode = 'ay'">aym</xsl:when>
								<xsl:when test="$myLanguageCode = 'az'">aze</xsl:when>
								<xsl:when test="$myLanguageCode = 'bm'">bam</xsl:when>
								<xsl:when test="$myLanguageCode = 'ba'">bak</xsl:when>
								<xsl:when test="$myLanguageCode = 'eu'">baq</xsl:when>
								<xsl:when test="$myLanguageCode = 'be'">bel</xsl:when>
								<xsl:when test="$myLanguageCode = 'bn'">ben</xsl:when>
								<xsl:when test="$myLanguageCode = 'bh'">bih</xsl:when>
								<xsl:when test="$myLanguageCode = 'bi'">bis</xsl:when>
								<xsl:when test="$myLanguageCode = 'bs'">bos</xsl:when>
								<xsl:when test="$myLanguageCode = 'br'">bre</xsl:when>
								<xsl:when test="$myLanguageCode = 'bg'">bul</xsl:when>
								<xsl:when test="$myLanguageCode = 'my'">bur</xsl:when>
								<xsl:when test="$myLanguageCode = 'ca'">cat</xsl:when>
								<xsl:when test="$myLanguageCode = 'ch'">cha</xsl:when>
								<xsl:when test="$myLanguageCode = 'ce'">che</xsl:when>
								<xsl:when test="$myLanguageCode = 'ny'">nya</xsl:when>
								<xsl:when test="$myLanguageCode = 'zh'">chi</xsl:when>
								<xsl:when test="$myLanguageCode = 'cv'">chv</xsl:when>
								<xsl:when test="$myLanguageCode = 'kw'">cor</xsl:when>
								<xsl:when test="$myLanguageCode = 'co'">cos</xsl:when>
								<xsl:when test="$myLanguageCode = 'cr'">cre</xsl:when>
								<xsl:when test="$myLanguageCode = 'hr'">hrv</xsl:when>
								<xsl:when test="$myLanguageCode = 'cs'">cze</xsl:when>
								<xsl:when test="$myLanguageCode = 'da'">dan</xsl:when>
								<xsl:when test="$myLanguageCode = 'dv'">div</xsl:when>
								<xsl:when test="$myLanguageCode = 'nl'">dut</xsl:when>
								<xsl:when test="$myLanguageCode = 'dz'">dzo</xsl:when>
								<xsl:when test="$myLanguageCode = 'en'">eng</xsl:when>
								<xsl:when test="$myLanguageCode = 'eo'">epo</xsl:when>
								<xsl:when test="$myLanguageCode = 'et'">est</xsl:when>
								<xsl:when test="$myLanguageCode = 'ee'">ewe</xsl:when>
								<xsl:when test="$myLanguageCode = 'fo'">fao</xsl:when>
								<xsl:when test="$myLanguageCode = 'fj'">fij</xsl:when>
								<xsl:when test="$myLanguageCode = 'fi'">fin</xsl:when>
								<xsl:when test="$myLanguageCode = 'fr'">fre</xsl:when>
								<xsl:when test="$myLanguageCode = 'ff'">ful</xsl:when>
								<xsl:when test="$myLanguageCode = 'gl'">glg</xsl:when>
								<xsl:when test="$myLanguageCode = 'ka'">geo</xsl:when>
								<xsl:when test="$myLanguageCode = 'de'">ger</xsl:when>
								<xsl:when test="$myLanguageCode = 'el'">gre</xsl:when>
								<xsl:when test="$myLanguageCode = 'gn'">grn</xsl:when>
								<xsl:when test="$myLanguageCode = 'gu'">guj</xsl:when>
								<xsl:when test="$myLanguageCode = 'ht'">hat</xsl:when>
								<xsl:when test="$myLanguageCode = 'ha'">hau</xsl:when>
								<xsl:when test="$myLanguageCode = 'he'">heb</xsl:when>
								<xsl:when test="$myLanguageCode = 'hz'">her</xsl:when>
								<xsl:when test="$myLanguageCode = 'hi'">hin</xsl:when>
								<xsl:when test="$myLanguageCode = 'ho'">hmo</xsl:when>
								<xsl:when test="$myLanguageCode = 'hu'">hun</xsl:when>
								<xsl:when test="$myLanguageCode = 'ia'">ina</xsl:when>
								<xsl:when test="$myLanguageCode = 'id'">ind</xsl:when>
								<xsl:when test="$myLanguageCode = 'ie'">ile</xsl:when>
								<xsl:when test="$myLanguageCode = 'ga'">gle</xsl:when>
								<xsl:when test="$myLanguageCode = 'ig'">ibo</xsl:when>
								<xsl:when test="$myLanguageCode = 'ik'">ipk</xsl:when>
								<xsl:when test="$myLanguageCode = 'io'">ido</xsl:when>
								<xsl:when test="$myLanguageCode = 'is'">ice</xsl:when>
								<xsl:when test="$myLanguageCode = 'it'">ita</xsl:when>
								<xsl:when test="$myLanguageCode = 'iu'">iku</xsl:when>
								<xsl:when test="$myLanguageCode = 'ja'">jpn</xsl:when>
								<xsl:when test="$myLanguageCode = 'jv'">jav</xsl:when>
								<xsl:when test="$myLanguageCode = 'kl'">kal</xsl:when>
								<xsl:when test="$myLanguageCode = 'kn'">kan</xsl:when>
								<xsl:when test="$myLanguageCode = 'kr'">kau</xsl:when>
								<xsl:when test="$myLanguageCode = 'ks'">kas</xsl:when>
								<xsl:when test="$myLanguageCode = 'kk'">kaz</xsl:when>
								<xsl:when test="$myLanguageCode = 'km'">khm</xsl:when>
								<xsl:when test="$myLanguageCode = 'ki'">kik</xsl:when>
								<xsl:when test="$myLanguageCode = 'rw'">kin</xsl:when>
								<xsl:when test="$myLanguageCode = 'ky'">kir</xsl:when>
								<xsl:when test="$myLanguageCode = 'kv'">kom</xsl:when>
								<xsl:when test="$myLanguageCode = 'kg'">kon</xsl:when>
								<xsl:when test="$myLanguageCode = 'ko'">kor</xsl:when>
								<xsl:when test="$myLanguageCode = 'ku'">kur</xsl:when>
								<xsl:when test="$myLanguageCode = 'kj'">kua</xsl:when>
								<xsl:when test="$myLanguageCode = 'la'">lat</xsl:when>
								<xsl:when test="$myLanguageCode = 'lb'">ltz</xsl:when>
								<xsl:when test="$myLanguageCode = 'lg'">lug</xsl:when>
								<xsl:when test="$myLanguageCode = 'li'">lim</xsl:when>
								<xsl:when test="$myLanguageCode = 'ln'">lin</xsl:when>
								<xsl:when test="$myLanguageCode = 'lo'">lao</xsl:when>
								<xsl:when test="$myLanguageCode = 'lt'">lit</xsl:when>
								<xsl:when test="$myLanguageCode = 'lu'">lub</xsl:when>
								<xsl:when test="$myLanguageCode = 'lv'">lav</xsl:when>
								<xsl:when test="$myLanguageCode = 'gv'">glv</xsl:when>
								<xsl:when test="$myLanguageCode = 'mk'">mac</xsl:when>
								<xsl:when test="$myLanguageCode = 'mg'">mlg</xsl:when>
								<xsl:when test="$myLanguageCode = 'ms'">may</xsl:when>
								<xsl:when test="$myLanguageCode = 'ml'">mal</xsl:when>
								<xsl:when test="$myLanguageCode = 'mt'">mlt</xsl:when>
								<xsl:when test="$myLanguageCode = 'mi'">mao</xsl:when>
								<xsl:when test="$myLanguageCode = 'mr'">mar</xsl:when>
								<xsl:when test="$myLanguageCode = 'mh'">mah</xsl:when>
								<xsl:when test="$myLanguageCode = 'mn'">mon</xsl:when>
								<xsl:when test="$myLanguageCode = 'na'">nau</xsl:when>
								<xsl:when test="$myLanguageCode = 'nv'">nav</xsl:when>
								<xsl:when test="$myLanguageCode = 'nb'">nob</xsl:when>
								<xsl:when test="$myLanguageCode = 'nd'">nde</xsl:when>
								<xsl:when test="$myLanguageCode = 'ne'">nep</xsl:when>
								<xsl:when test="$myLanguageCode = 'ng'">ndo</xsl:when>
								<xsl:when test="$myLanguageCode = 'nn'">nno</xsl:when>
								<xsl:when test="$myLanguageCode = 'no'">nor</xsl:when>
								<xsl:when test="$myLanguageCode = 'ii'">iii</xsl:when>
								<xsl:when test="$myLanguageCode = 'nr'">nbl</xsl:when>
								<xsl:when test="$myLanguageCode = 'oc'">oci</xsl:when>
								<xsl:when test="$myLanguageCode = 'oj'">oji</xsl:when>
								<xsl:when test="$myLanguageCode = 'cu'">chu</xsl:when>
								<xsl:when test="$myLanguageCode = 'om'">orm</xsl:when>
								<xsl:when test="$myLanguageCode = 'or'">ori</xsl:when>
								<xsl:when test="$myLanguageCode = 'os'">oss</xsl:when>
								<xsl:when test="$myLanguageCode = 'pa'">pan</xsl:when>
								<xsl:when test="$myLanguageCode = 'pi'">pli</xsl:when>
								<xsl:when test="$myLanguageCode = 'fa'">per</xsl:when>
								<xsl:when test="$myLanguageCode = 'pl'">pol</xsl:when>
								<xsl:when test="$myLanguageCode = 'ps'">pus</xsl:when>
								<xsl:when test="$myLanguageCode = 'pt'">por</xsl:when>
								<xsl:when test="$myLanguageCode = 'qu'">que</xsl:when>
								<xsl:when test="$myLanguageCode = 'rm'">roh</xsl:when>
								<xsl:when test="$myLanguageCode = 'rn'">run</xsl:when>
								<xsl:when test="$myLanguageCode = 'ro'">rum</xsl:when>
								<xsl:when test="$myLanguageCode = 'ru'">rus</xsl:when>
								<xsl:when test="$myLanguageCode = 'sa'">san</xsl:when>
								<xsl:when test="$myLanguageCode = 'sc'">srd</xsl:when>
								<xsl:when test="$myLanguageCode = 'sd'">snd</xsl:when>
								<xsl:when test="$myLanguageCode = 'se'">sme</xsl:when>
								<xsl:when test="$myLanguageCode = 'sm'">smo</xsl:when>
								<xsl:when test="$myLanguageCode = 'sg'">sag</xsl:when>
								<xsl:when test="$myLanguageCode = 'sr'">srp</xsl:when>
								<xsl:when test="$myLanguageCode = 'gd'">gla</xsl:when>
								<xsl:when test="$myLanguageCode = 'sn'">sna</xsl:when>
								<xsl:when test="$myLanguageCode = 'si'">sin</xsl:when>
								<xsl:when test="$myLanguageCode = 'sk'">slo</xsl:when>
								<xsl:when test="$myLanguageCode = 'sl'">slv</xsl:when>
								<xsl:when test="$myLanguageCode = 'so'">som</xsl:when>
								<xsl:when test="$myLanguageCode = 'st'">sot</xsl:when>
								<xsl:when test="$myLanguageCode = 'es'">spa</xsl:when>
								<xsl:when test="$myLanguageCode = 'su'">sun</xsl:when>
								<xsl:when test="$myLanguageCode = 'sw'">swa</xsl:when>
								<xsl:when test="$myLanguageCode = 'ss'">ssw</xsl:when>
								<xsl:when test="$myLanguageCode = 'sv'">swe</xsl:when>
								<xsl:when test="$myLanguageCode = 'ta'">tam</xsl:when>
								<xsl:when test="$myLanguageCode = 'te'">tel</xsl:when>
								<xsl:when test="$myLanguageCode = 'tg'">tgk</xsl:when>
								<xsl:when test="$myLanguageCode = 'th'">tha</xsl:when>
								<xsl:when test="$myLanguageCode = 'ti'">tir</xsl:when>
								<xsl:when test="$myLanguageCode = 'bo'">tib</xsl:when>
								<xsl:when test="$myLanguageCode = 'tk'">tuk</xsl:when>
								<xsl:when test="$myLanguageCode = 'tl'">tgl</xsl:when>
								<xsl:when test="$myLanguageCode = 'tn'">tsn</xsl:when>
								<xsl:when test="$myLanguageCode = 'to'">ton</xsl:when>
								<xsl:when test="$myLanguageCode = 'tr'">tur</xsl:when>
								<xsl:when test="$myLanguageCode = 'ts'">tso</xsl:when>
								<xsl:when test="$myLanguageCode = 'tt'">tat</xsl:when>
								<xsl:when test="$myLanguageCode = 'tw'">twi</xsl:when>
								<xsl:when test="$myLanguageCode = 'ty'">tah</xsl:when>
								<xsl:when test="$myLanguageCode = 'ug'">uig</xsl:when>
								<xsl:when test="$myLanguageCode = 'uk'">ukr</xsl:when>
								<xsl:when test="$myLanguageCode = 'ur'">urd</xsl:when>
								<xsl:when test="$myLanguageCode = 'uz'">uzb</xsl:when>
								<xsl:when test="$myLanguageCode = 've'">ven</xsl:when>
								<xsl:when test="$myLanguageCode = 'vi'">vie</xsl:when>
								<xsl:when test="$myLanguageCode = 'vo'">vol</xsl:when>
								<xsl:when test="$myLanguageCode = 'wa'">wln</xsl:when>
								<xsl:when test="$myLanguageCode = 'cy'">wel</xsl:when>
								<xsl:when test="$myLanguageCode = 'wo'">wol</xsl:when>
								<xsl:when test="$myLanguageCode = 'fy'">fry</xsl:when>
								<xsl:when test="$myLanguageCode = 'xh'">xho</xsl:when>
								<xsl:when test="$myLanguageCode = 'yi'">yid</xsl:when>
								<xsl:when test="$myLanguageCode = 'yo'">yor</xsl:when>
								<xsl:when test="$myLanguageCode = 'za'">zha</xsl:when>
								<xsl:when test="$myLanguageCode = 'zu'">zul</xsl:when>
								<xsl:when test="$myLanguageCode = 'ab'">abk</xsl:when>
								<xsl:when test="$myLanguageCode = 'aa'">aar</xsl:when>
								<xsl:when test="$myLanguageCode = 'af'">afr</xsl:when>
								<xsl:when test="$myLanguageCode = 'ak'">aka</xsl:when>
								<xsl:when test="$myLanguageCode = 'sq'">alb</xsl:when>
								<xsl:when test="$myLanguageCode = 'am'">amh</xsl:when>
								<xsl:when test="$myLanguageCode = 'ar'">ara</xsl:when>
								<xsl:when test="$myLanguageCode = 'an'">arg</xsl:when>
								<xsl:when test="$myLanguageCode = 'hy'">arm</xsl:when>
								<xsl:when test="$myLanguageCode = 'as'">asm</xsl:when>
								<xsl:when test="$myLanguageCode = 'av'">ava</xsl:when>
								<xsl:when test="$myLanguageCode = 'ae'">ave</xsl:when>
								<xsl:when test="$myLanguageCode = 'ay'">aym</xsl:when>
								<xsl:when test="$myLanguageCode = 'az'">aze</xsl:when>
								<xsl:when test="$myLanguageCode = 'bm'">bam</xsl:when>
								<xsl:when test="$myLanguageCode = 'ba'">bak</xsl:when>
								<xsl:when test="$myLanguageCode = 'eu'">baq</xsl:when>
								<xsl:when test="$myLanguageCode = 'be'">bel</xsl:when>
								<xsl:when test="$myLanguageCode = 'bn'">ben</xsl:when>
								<xsl:when test="$myLanguageCode = 'bh'">bih</xsl:when>
								<xsl:when test="$myLanguageCode = 'bi'">bis</xsl:when>
								<xsl:when test="$myLanguageCode = 'bs'">bos</xsl:when>
								<xsl:when test="$myLanguageCode = 'br'">bre</xsl:when>
								<xsl:when test="$myLanguageCode = 'bg'">bul</xsl:when>
								<xsl:when test="$myLanguageCode = 'my'">bur</xsl:when>
								<xsl:when test="$myLanguageCode = 'ca'">cat</xsl:when>
								<xsl:when test="$myLanguageCode = 'ch'">cha</xsl:when>
								<xsl:when test="$myLanguageCode = 'ce'">che</xsl:when>
								<xsl:when test="$myLanguageCode = 'ny'">nya</xsl:when>
								<xsl:when test="$myLanguageCode = 'zh'">chi</xsl:when>
								<xsl:when test="$myLanguageCode = 'cv'">chv</xsl:when>
								<xsl:when test="$myLanguageCode = 'kw'">cor</xsl:when>
								<xsl:when test="$myLanguageCode = 'co'">cos</xsl:when>
								<xsl:when test="$myLanguageCode = 'cr'">cre</xsl:when>
								<xsl:when test="$myLanguageCode = 'hr'">hrv</xsl:when>
								<xsl:when test="$myLanguageCode = 'cs'">cze</xsl:when>
								<xsl:when test="$myLanguageCode = 'da'">dan</xsl:when>
								<xsl:when test="$myLanguageCode = 'dv'">div</xsl:when>
								<xsl:when test="$myLanguageCode = 'nl'">dut</xsl:when>
								<xsl:when test="$myLanguageCode = 'dz'">dzo</xsl:when>
								<xsl:when test="$myLanguageCode = 'en'">eng</xsl:when>
								<xsl:when test="$myLanguageCode = 'eo'">epo</xsl:when>
								<xsl:when test="$myLanguageCode = 'et'">est</xsl:when>
								<xsl:when test="$myLanguageCode = 'ee'">ewe</xsl:when>
								<xsl:when test="$myLanguageCode = 'fo'">fao</xsl:when>
								<xsl:when test="$myLanguageCode = 'fj'">fij</xsl:when>
								<xsl:when test="$myLanguageCode = 'fi'">fin</xsl:when>
								<xsl:when test="$myLanguageCode = 'fr'">fre</xsl:when>
								<xsl:when test="$myLanguageCode = 'ff'">ful</xsl:when>
								<xsl:when test="$myLanguageCode = 'gl'">glg</xsl:when>
								<xsl:when test="$myLanguageCode = 'ka'">geo</xsl:when>
								<xsl:when test="$myLanguageCode = 'de'">ger</xsl:when>
								<xsl:when test="$myLanguageCode = 'el'">gre</xsl:when>
								<xsl:when test="$myLanguageCode = 'gn'">grn</xsl:when>
								<xsl:when test="$myLanguageCode = 'gu'">guj</xsl:when>
								<xsl:when test="$myLanguageCode = 'ht'">hat</xsl:when>
								<xsl:when test="$myLanguageCode = 'ha'">hau</xsl:when>
								<xsl:when test="$myLanguageCode = 'he'">heb</xsl:when>
								<xsl:when test="$myLanguageCode = 'hz'">her</xsl:when>
								<xsl:when test="$myLanguageCode = 'hi'">hin</xsl:when>
								<xsl:when test="$myLanguageCode = 'ho'">hmo</xsl:when>
								<xsl:when test="$myLanguageCode = 'hu'">hun</xsl:when>
								<xsl:when test="$myLanguageCode = 'ia'">ina</xsl:when>
								<xsl:when test="$myLanguageCode = 'id'">ind</xsl:when>
								<xsl:when test="$myLanguageCode = 'ie'">ile</xsl:when>
								<xsl:when test="$myLanguageCode = 'ga'">gle</xsl:when>
								<xsl:when test="$myLanguageCode = 'ig'">ibo</xsl:when>
								<xsl:when test="$myLanguageCode = 'ik'">ipk</xsl:when>
								<xsl:when test="$myLanguageCode = 'io'">ido</xsl:when>
								<xsl:when test="$myLanguageCode = 'is'">ice</xsl:when>
								<xsl:when test="$myLanguageCode = 'it'">ita</xsl:when>
								<xsl:when test="$myLanguageCode = 'iu'">iku</xsl:when>
								<xsl:when test="$myLanguageCode = 'ja'">jpn</xsl:when>
								<xsl:when test="$myLanguageCode = 'jv'">jav</xsl:when>
								<xsl:when test="$myLanguageCode = 'kl'">kal</xsl:when>
								<xsl:when test="$myLanguageCode = 'kn'">kan</xsl:when>
								<xsl:when test="$myLanguageCode = 'kr'">kau</xsl:when>
								<xsl:when test="$myLanguageCode = 'ks'">kas</xsl:when>
								<xsl:when test="$myLanguageCode = 'kk'">kaz</xsl:when>
								<xsl:when test="$myLanguageCode = 'km'">khm</xsl:when>
								<xsl:when test="$myLanguageCode = 'ki'">kik</xsl:when>
								<xsl:when test="$myLanguageCode = 'rw'">kin</xsl:when>
								<xsl:when test="$myLanguageCode = 'ky'">kir</xsl:when>
								<xsl:when test="$myLanguageCode = 'kv'">kom</xsl:when>
								<xsl:when test="$myLanguageCode = 'kg'">kon</xsl:when>
								<xsl:when test="$myLanguageCode = 'ko'">kor</xsl:when>
								<xsl:when test="$myLanguageCode = 'ku'">kur</xsl:when>
								<xsl:when test="$myLanguageCode = 'kj'">kua</xsl:when>
								<xsl:when test="$myLanguageCode = 'la'">lat</xsl:when>
								<xsl:when test="$myLanguageCode = 'lb'">ltz</xsl:when>
								<xsl:when test="$myLanguageCode = 'lg'">lug</xsl:when>
								<xsl:when test="$myLanguageCode = 'li'">lim</xsl:when>
								<xsl:when test="$myLanguageCode = 'ln'">lin</xsl:when>
								<xsl:when test="$myLanguageCode = 'lo'">lao</xsl:when>
								<xsl:when test="$myLanguageCode = 'lt'">lit</xsl:when>
								<xsl:when test="$myLanguageCode = 'lu'">lub</xsl:when>
								<xsl:when test="$myLanguageCode = 'lv'">lav</xsl:when>
								<xsl:when test="$myLanguageCode = 'gv'">glv</xsl:when>
								<xsl:when test="$myLanguageCode = 'mk'">mac</xsl:when>
								<xsl:when test="$myLanguageCode = 'mg'">mlg</xsl:when>
								<xsl:when test="$myLanguageCode = 'ms'">may</xsl:when>
								<xsl:when test="$myLanguageCode = 'ml'">mal</xsl:when>
								<xsl:when test="$myLanguageCode = 'mt'">mlt</xsl:when>
								<xsl:when test="$myLanguageCode = 'mi'">mao</xsl:when>
								<xsl:when test="$myLanguageCode = 'mr'">mar</xsl:when>
								<xsl:when test="$myLanguageCode = 'mh'">mah</xsl:when>
								<xsl:when test="$myLanguageCode = 'mn'">mon</xsl:when>
								<xsl:when test="$myLanguageCode = 'na'">nau</xsl:when>
								<xsl:when test="$myLanguageCode = 'nv'">nav</xsl:when>
								<xsl:when test="$myLanguageCode = 'nb'">nob</xsl:when>
								<xsl:when test="$myLanguageCode = 'nd'">nde</xsl:when>
								<xsl:when test="$myLanguageCode = 'ne'">nep</xsl:when>
								<xsl:when test="$myLanguageCode = 'ng'">ndo</xsl:when>
								<xsl:when test="$myLanguageCode = 'nn'">nno</xsl:when>
								<xsl:when test="$myLanguageCode = 'no'">nor</xsl:when>
								<xsl:when test="$myLanguageCode = 'ii'">iii</xsl:when>
								<xsl:when test="$myLanguageCode = 'nr'">nbl</xsl:when>
								<xsl:when test="$myLanguageCode = 'oc'">oci</xsl:when>
								<xsl:when test="$myLanguageCode = 'oj'">oji</xsl:when>
								<xsl:when test="$myLanguageCode = 'cu'">chu</xsl:when>
								<xsl:when test="$myLanguageCode = 'om'">orm</xsl:when>
								<xsl:when test="$myLanguageCode = 'or'">ori</xsl:when>
								<xsl:when test="$myLanguageCode = 'os'">oss</xsl:when>
								<xsl:when test="$myLanguageCode = 'pa'">pan</xsl:when>
								<xsl:when test="$myLanguageCode = 'pi'">pli</xsl:when>
								<xsl:when test="$myLanguageCode = 'fa'">per</xsl:when>
								<xsl:when test="$myLanguageCode = 'pl'">pol</xsl:when>
								<xsl:when test="$myLanguageCode = 'ps'">pus</xsl:when>
								<xsl:when test="$myLanguageCode = 'pt'">por</xsl:when>
								<xsl:when test="$myLanguageCode = 'qu'">que</xsl:when>
								<xsl:when test="$myLanguageCode = 'rm'">roh</xsl:when>
								<xsl:when test="$myLanguageCode = 'rn'">run</xsl:when>
								<xsl:when test="$myLanguageCode = 'ro'">rum</xsl:when>
								<xsl:when test="$myLanguageCode = 'ru'">rus</xsl:when>
								<xsl:when test="$myLanguageCode = 'sa'">san</xsl:when>
								<xsl:when test="$myLanguageCode = 'sc'">srd</xsl:when>
								<xsl:when test="$myLanguageCode = 'sd'">snd</xsl:when>
								<xsl:when test="$myLanguageCode = 'se'">sme</xsl:when>
								<xsl:when test="$myLanguageCode = 'sm'">smo</xsl:when>
								<xsl:when test="$myLanguageCode = 'sg'">sag</xsl:when>
								<xsl:when test="$myLanguageCode = 'sr'">srp</xsl:when>
								<xsl:when test="$myLanguageCode = 'gd'">gla</xsl:when>
								<xsl:when test="$myLanguageCode = 'sn'">sna</xsl:when>
								<xsl:when test="$myLanguageCode = 'si'">sin</xsl:when>
								<xsl:when test="$myLanguageCode = 'sk'">slo</xsl:when>
								<xsl:when test="$myLanguageCode = 'sl'">slv</xsl:when>
								<xsl:when test="$myLanguageCode = 'so'">som</xsl:when>
								<xsl:when test="$myLanguageCode = 'st'">sot</xsl:when>
								<xsl:when test="$myLanguageCode = 'es'">spa</xsl:when>
								<xsl:when test="$myLanguageCode = 'su'">sun</xsl:when>
								<xsl:when test="$myLanguageCode = 'sw'">swa</xsl:when>
								<xsl:when test="$myLanguageCode = 'ss'">ssw</xsl:when>
								<xsl:when test="$myLanguageCode = 'sv'">swe</xsl:when>
								<xsl:when test="$myLanguageCode = 'ta'">tam</xsl:when>
								<xsl:when test="$myLanguageCode = 'te'">tel</xsl:when>
								<xsl:when test="$myLanguageCode = 'tg'">tgk</xsl:when>
								<xsl:when test="$myLanguageCode = 'th'">tha</xsl:when>
								<xsl:when test="$myLanguageCode = 'ti'">tir</xsl:when>
								<xsl:when test="$myLanguageCode = 'bo'">tib</xsl:when>
								<xsl:when test="$myLanguageCode = 'tk'">tuk</xsl:when>
								<xsl:when test="$myLanguageCode = 'tl'">tgl</xsl:when>
								<xsl:when test="$myLanguageCode = 'tn'">tsn</xsl:when>
								<xsl:when test="$myLanguageCode = 'to'">ton</xsl:when>
								<xsl:when test="$myLanguageCode = 'tr'">tur</xsl:when>
								<xsl:when test="$myLanguageCode = 'ts'">tso</xsl:when>
								<xsl:when test="$myLanguageCode = 'tt'">tat</xsl:when>
								<xsl:when test="$myLanguageCode = 'tw'">twi</xsl:when>
								<xsl:when test="$myLanguageCode = 'ty'">tah</xsl:when>
								<xsl:when test="$myLanguageCode = 'ug'">uig</xsl:when>
								<xsl:when test="$myLanguageCode = 'uk'">ukr</xsl:when>
								<xsl:when test="$myLanguageCode = 'ur'">urd</xsl:when>
								<xsl:when test="$myLanguageCode = 'uz'">uzb</xsl:when>
								<xsl:when test="$myLanguageCode = 've'">ven</xsl:when>
								<xsl:when test="$myLanguageCode = 'vi'">vie</xsl:when>
								<xsl:when test="$myLanguageCode = 'vo'">vol</xsl:when>
								<xsl:when test="$myLanguageCode = 'wa'">wln</xsl:when>
								<xsl:when test="$myLanguageCode = 'cy'">wel</xsl:when>
								<xsl:when test="$myLanguageCode = 'wo'">wol</xsl:when>
								<xsl:when test="$myLanguageCode = 'fy'">fry</xsl:when>
								<xsl:when test="$myLanguageCode = 'xh'">xho</xsl:when>
								<xsl:when test="$myLanguageCode = 'yi'">yid</xsl:when>
								<xsl:when test="$myLanguageCode = 'yo'">yor</xsl:when>
								<xsl:when test="$myLanguageCode = 'za'">zha</xsl:when>
								<xsl:when test="$myLanguageCode = 'zu'">zul</xsl:when>
							</xsl:choose>
							</xsl:template>
</xsl:stylesheet>
